### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by rapgenic** [semlanik/qtprotobuf#145]
Right now it seems to me that QtProtobuf supports only Http2 transport for exchanging data with the server. However in my application I'd like to be able to use the Unix socket as well. 

I can see that there is a base class for the channels: `QAbstractGrpcChannel`. Should the class implementing the unix socket be derived from that? I was thinking about using QLocalSocket as a the low level class for handling socket logic, but I could not find any documentation about the protocol.

Have you made any progress in implementing a Unix socket transport or do you have any suggestion on how I could begin implementing it?

If you could point me in the right direction that would be great!

**Comment by semlanik** [comment]
Hi @rapgenic,

At transport level you need both server and client side support. С++ gRPC it self supports only 3 types of transport:
https://github.com/grpc/grpc/tree/master/src/core/ext/transport

So current implementation of QtGrpc supports only HTTP/2, cronet and inproc are out of scope for now, especially inproc.

Meanwhile QtGrpc doesn't implement server API as for now, that's why for QtGrpc client HTTP/2 is the only option. The plan is to implement corresponding server stub generation and basic server-side abstract gRPC channel this year. I'm not sure about HTTP/2 support, since the only option I see for server is usage of 3rd-party library like nghttp2.

Also there was an idea to use ZeroMQ for one of possible transports. But unix sockets are also good choice for implementation.

**As resume:**
- It's not possible to use unix sockets across existing gRPC infrastructure.
- It would be possible to unix sockets with QtGrpc once server-side API will be implemented as well as any other transport that you would like to use.

**Now about the way you may reach you target**

You may implement own transport based on unix sockets by implementing QAbstractGrpcChannel interface. There are few virtual methods that should be implemented for success work, it's not a big deal to be honest. Establishing connection etc. is up to implementation as you could see for HTTP2.

In situation I described above you also need to implement same channel for server framework that you use. Here I could not help much because didn't touch this part of gRPC yet. But I saw this possibility for Kotlin/JAVA at least, guess it's possible to implement own server-side transport for other languages as well.

**Warning**
While server-side gRPC implementation I expect some impact on existing client-side API. I didn't think on design yet, but it's kind of feeling that I have :). And to be clear, I do not stop you of implementation, even vice versa I'm glad to include UNIX-socket transport into the project. Also it might be used as reference implementation for server as well in future.

**Comment by rapgenic** [comment]
@semlanik Thank you for your quick and complete answer! 

> At transport level you need both server and client side support. С++ gRPC it self supports only 3 types of transport:
https://github.com/grpc/grpc/tree/master/src/core/ext/transport

Your answer made me realise that gRPC on unix socket (which is _by default_ supported by gRPC) is in fact a **HTTP connection over a unix socket instead of a tcp socket**.

This is how it's done in C++ gRPC:
```c++
ServerBuilder builder;
builder.AddListeningPort("0.0.0.0:50051", grpc::InsecureServerCredentials());               // Both of these
builder.AddListeningPort("unix://var/run/test.sock", grpc::InsecureServerCredentials());    // are valid
```

This means that the changes should be related more to QNetworkAccessManager rather than QtProtobuf, and I'd need to find a way to make QNetworkAccessManager use a unix socket as well, rather than only a tcp socket.

I have seen (https://stackoverflow.com/questions/48655224/qt-http-request-over-a-unix-socket) that this should be possible by subclassing QNetworkAccessManager and QNetworkReply to do this. If this is actually possible (the author only mentioned he could do it but not how...) I think that those custom classes could be included in QtProtobuf.

Of course I am using client side only, so everything I mentioned might not be applicable to the server side, which as I understand hasn't still been written. 

I will keep you updated on my progress if something interesting arises and I'll try to make a pull request if I am able to get it done nicely.

**Comment by semlanik** [comment]
@rapgenic , ok it seems was my point of misunderstanding. I thought you would like pure unix sockets as transport mechanism without HTTP2 involved. I have feeling that QGrpcHttp2Channel("unix://var/run/test.sock", QGrpcInsecureChannelCredentials() | QGrpcInsecureCallCredentials())) might work for you :)

**Comment by semlanik** [comment]
@rapgenic , I found out that my statement above is incorrect, because of QtGrpc check that I placed previously:

https://github.com/semlanik/qtprotobuf/blob/master/src/grpc/qgrpchttp2channel.cpp#L182

So probably if you will remove this checks and replacement of URL scheme, it will work.

**Comment by rapgenic** [comment]
Sadly that was the first thing I tried... with no success (even without your check): in fact looking at the Qt source code it seems that the "unix://" schema is not supported. Please tell me if I am missing something, but I fear that it is not possibile right now.

**Comment by rapgenic** [comment]
Hi @semlanik, I wanted to give you an update on my progress. I ended up abandoning the idea to adapt the QNetworkAccessManager to send its requests through the unix socket (Qt code is too complex to patch it or subclass the right classes in a little time). 

Instead I subclassed `QAbstractGrpcChannel` creating a new class which is basically a wrapper around the gRPC C++ library. In this way, using the grpc::Channel class under the hood, I can use both the tcp and the unix socket.

I don't know if you are interested in this way of handling the gRPC communication, however if so please tell me and I'll polish the code and open a pull request

**Comment by semlanik** [comment]
Hi @rapgenic , I think we could include it into the project as well, but because it's new dependency for the libraries, probably I will put it under some option later on.
